### ISSUE TITLE
Logging - Debugging Purposes

### ISSUE THREAD

**Issue by aconite33** [hexmode/mediawiki-LDAP#1]
Is it possible to add a logging function? I'm trying to test out this extension to replace the old LDAPExtension for Mediawiki. I believe I've set everything up correctly but I'm unable to get any output to determine where the authentication is failing.

**Comment by hexmode** [comment]
I'm abandoning this and working on https://github.com/MWStake/mediawiki-extensions-LDAPProvider/ and related extensions.
